### ISSUE TITLE
Eintragsdetails richtig ausrichten

### ISSUE THREAD

**Issue by wellemut** [alex0107/karte_von_morgen-die_app#12]
- auf der Eintragsseite (Bild 3): webseite, Adresse, Routenplaner und so sollten aneinander ausgerichtet sein, also den gleichen Abstand vom linken Bildschirmrand sozusagen. Die Icons davor sollten in divs gleicher Breite sein und darin zentriert. (momentan sind die Icons linksbündig und da das Pin-Icon eine andere Breite hat als das Routenplaner-Icon fällt das auf.)

![photo5447344147670347152](https://user-images.githubusercontent.com/15019030/53300316-d50feb80-3845-11e9-8a38-b90eac0e8013.jpg)

**Comment by alex0107** [comment]
Kommt in Version 1.2.2
