### ISSUE TITLE
OSM Copyright

### ISSUE THREAD

**Issue by wellemut** [alex0107/karte_von_morgen-die_app#20]
Add the correct copyright in the bottom right corner. 
Leaflet | © OpenStreetMap.
Do it the same way as on kartevonmorgen.org

(Laut einem Twitter nutze muss unten rechts in der App der osm copyright Hinweis stehen https://twitter.com/carstenhag/status/1169726779818467335?s=19)

**Comment by alex0107** [comment]
Next Version will fix this
