### ISSUE TITLE
Iphone 6 problem, that nothing is shown

### ISSUE THREAD

**Issue by wellemut** [alex0107/karte_von_morgen-die_app#21]
### Das war gerade ein Feedback zu Refill von Stephanie, der Gründerin
Ich habe gestern mit dem Iphone (6) in der App versucht klar zu kommen.

Ich sehe keine Marker wenn ich die Karte aufrufe

Erst wenn ich meinen Standpunkt aufrufe sehe ich einige Marker und eine Liste ( di nur manchmal scrollbar ist)

wenn ich die Karte verändere passen sich die Marker nicht an
-wenn ich in der Übersicht suche nach #refill passiert nichts.

es ist nicht möglich in einer anderen Stadt zu suchen.

Es entsteht der Eindruck es gibt kaum Marker

@helmutwo kannst du den Entwickler hierhin einladen? Oder uns mit ihm verknüpfen?

@helmutwo ich habe gerade neu installiert aber das hilft nichts. Ich sehe die Karte mit den Marker nicht.

Ja die globale Suche habe ich auch bemüht (ich habe wirklich stundenlang alles ausprobiert)
Aber auf der Karte passiert nichts. Wenn ich versuche in der Karte zu suchen springe ich immer auf die Liste zurück.

aaah die Stadtsuche funktioniert aber nicht gefiltert nach Refill.

Frage ist momentan ob wir die App überhaupt ankündigen können.
Ich werde nicht die Einzige sein wo es Probleme gibt.

**Comment by alex0107** [comment]
Neue Version kommt bald (spät. morgen) hab noch paar Bugs gefunden
