### ISSUE TITLE
Do not jump to whole Germany after I searched in a city

### ISSUE THREAD

**Issue by wellemut** [alex0107/karte_von_morgen-die_app#22]
# Problem 
When I start to search in the list, I get local entries: 
![grafik](https://user-images.githubusercontent.com/15019030/66565034-c02c6200-eb61-11e9-9c50-c2cadb6ea8d0.png)

But when I click on the map-symbole, it shows all germany, but now maker
![grafik](https://user-images.githubusercontent.com/15019030/66565079-ddf9c700-eb61-11e9-8793-292827e89684.png)

See the video in the telegram group from Fr. 16.Aug. 19
# Solution
Die App started direkt in der aktuellen Position, wo auch pins angezeigt werden.
Über den localize me button oder die Ortssuche findet der nutzer dann eine andere Region und neue Pins werden geladen.

Auch wenn der nutzer rausszoom, sollten die lokalen einträge geladen bleiben.

**Comment by alex0107** [comment]
Next Version will fix this
