### ISSUE TITLE
Change city search symbols to a city

### ISSUE THREAD

**Issue by wellemut** [alex0107/karte_von_morgen-die_app#23]
# Problem 
We have the searchline and the location search at the bottom right, but both symbols are not to distignuish for new users.

# Solution
Integrate the citiy search in the same searchline (which is probaly too difficult) or Replace the citiy search button with a "city" symbol: https://origin.fontawesome.com/icons/city?style=solid
<i class="fas fa-city"></i>

**Comment by alex0107** [comment]
Next Version will fix this
