### ISSUE TITLE
Keine schlecht bewerteten Einträge in der App

### ISSUE THREAD

**Issue by wellemut** [alex0107/karte_von_morgen-die_app#3]
Hi Alex
Da es in der Karte keine Bewertungen gibt, die schlecht bewertete Einträge ganz nach unten verschiebt, müssen wir sicherstellen, dass schelchte Einträge erst gar nicht auf die App kommen.
Auf der online-Karte haben wir die Philosophie "Alles Kartieren - und wahrheitsgemäß bewerten" Gutes kommt hoch, schlechtes kommt runter. Ganz schlechtes soll einges tages auch ganz verschwinden.
Für die App würde ich vorschlagen, dass du gleich beim runterladen nach der Durchschnittsbewertung filterst und nur runterlädst, wo die Bewertung >=0 ist.

**Comment by alex0107** [comment]
Okay ich werde mich drum kümmern ;)

Bewertungen müssen >=0 sein.

**Comment by alex0107** [comment]
Ist jetzt in Version 1.0 im AppStore und PlayStore verfügbar.
