### ISSUE TITLE
license?

### ISSUE THREAD

**Issue by silberzwiebel** [alex0107/karte_von_morgen-die_app#5]
Thanks for your work! How is your source code licensed?

**Comment by alex0107** [comment]
We are searching for a solution.

**Comment by alex0107** [comment]
Our source code is licensed by CC-by-sa.
https://github.com/alex0107/karte_von_morgen-die_app/blob/master/LICENSE.md

**Comment by silberzwiebel** [comment]
Thanks! I just wanted to point out that [Creative Commons do not recommended the CC licenses for software](https://creativecommons.org/faq/#can-i-apply-a-creative-commons-license-to-software). You might want to switch to GPL for a similar software license (see links in the link above). But that's up to you of course, as it is your software.

**Comment by wellemut** [comment]
Why is it not recommended? What is the difference?

Helmut Wolman

(mailed on the move)
Mobil: 017647670833
Mannheim

kartoffelsalat <notifications@github.com> schrieb am Mo., 25. Feb. 2019
17:31:

**Comment by silberzwiebel** [comment]
Quoting from above's FAQ entry:

> "Unlike software-specific licenses, CC licenses do not contain specific terms about the distribution of source code, which is often important to ensuring the free reuse and modifiability of software. Many software licenses also address patent rights, which are important to software but may not be applicable to other copyrightable works. Additionally, our licenses are currently not compatible with the major software licenses, so it would be difficult to integrate CC-licensed work with other free software. Existing software licenses were designed specifically for use with software and offer a similar set of rights to the Creative Commons licenses."

A GPL license is also viral as a CC-SA license. That is, everyone has to open their sources under the same license if they use your source code. There are other licenses that don't have this feature (e.g., MIT license). This would be more similar to a CC0 license (kind of "do what you want with this"). Here is a [list of open source licenses](https://opensource.org/licenses).
